// Generated by agent-browser codegen
// Started: 2026-01-18T13:28:07.749Z
// Ended: 2026-01-18T13:28:35.928Z

await page.goto('https://www.saucedemo.com');
await page.locator('#user-name').fill('standard_user');
await page.locator('#password').fill('secret_sauce');
await page.locator('#login-button').click();